version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

workflows:
  version: 2.1
  workflow:
    jobs:
    - test
